version: '3.10'

services:
  flask-app:
    dns:
      - 8.8.8.8
      - 8.8.4.4
    build:
      context: ..
      dockerfile: Dockerfile
    container_name: ldrag-retriever-app
    ports:
      - "5000:5000"
    volumes:
      - ../ldrag:/app/ldrag
      - .:/app/gpt_chatbot_ldrag
    environment:
      - PYTHONUNBUFFERED=1
      - PYTHONPATH=/app
      - ldrag_openai_apikey
    restart: unless-stopped